### ISSUE TITLE
Imprevement Needed!

### ISSUE THREAD

**Issue by prabhatrsharma** [AKASH7233/Connectify#8]
Hello there, I used Connectify, it's awesome! Just wanted to tell you that the button at Home Page i.e. Login Page should named as ' 'Login' instead of 'Sign up', because as you may know that word 'Sign up' is for first time registration.

**Comment by AKASH7233** [comment]
Thanks, @prabhatrsharma  for your feedback !
I'll try to fix the issue ASAP
